# SPDX-FileCopyrightText: 2019 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
from_owner:
  - dependabot-preview[bot]
required_labels:
  - dependencies
apply_labels:
  - autoapproved
