# SPDX-FileCopyrightText: 2018 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run --enable-security-analysis

filter:
    excluded_paths:
        - 'l10n/*'
        - 'tests/'
        - 'vendor/*'

checks:
    php: true

tools:
    external_code_coverage:
        runs: 6
        timeout: 1200 # Timeout in seconds. 20 minutes
