# SPDX-FileCopyrightText: 2018 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
[package]
before_cmds = [
	"composer install --no-dev -o",
	"npm i",
	"npm run build",
]
