# SPDX-FileCopyrightText: 2022 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT
name: Release Test
on: push

jobs:
  release:
    permissions:
      contents: write
    runs-on: [ubuntu-latest, self-hosted]
    steps:
      - name: Checkout repository
        uses:  actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@67139193614f5b9e8db87da1bd4240922b34d765 # v6.0.0
        with:
          github-token: ${{ secrets.RELEASE_PAT }}
          skip-git-pull: "true"
          pre-commit: build/pre-commit.js
          release-count: 0
          version-file: "package.json, package-lock.json"
          git-push: false
      - name: Read package.json node and npm engines version
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        uses: skjnldsv/read-package-engines-version-actions@06d6baf7d8f41934ab630e97d9e6c0bc9c9ac5e4 # v3
        id: versions
        with:
          fallbackNode: '^16'
          fallbackNpm: '^8'
      - name: Set up Nextcloud env
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        uses: ChristophWurst/setup-nextcloud@fc0790385c175d97e88a7cb0933490de6e990374 # v0.3.2
        with:
          php-version: 'false'
          node-version: 'false'
          npm-version: ${{ steps.versions.outputs.npmVersion }}
          tools: 'krankerl'
